---
- name: Install mysqld python libary for Ansible
  package:
    name: python3-mysqldb
    state: present

- name: Install
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - mariadb-client
      - mariadb-common
      - mariadb-server

- name: Check if root password set
  command: mysql -u root --execute "SELECT NOW()"
  register: is_root_password_set
  ignore_errors: yes

- name: Delete anonymous users
  mysql_user:
    user: ""
    state: absent
  when: is_root_password_set.rc == 0

- name: Set the root password
  mysql_user:
    name: "root"
    password: "{{ mysql_root_password | mandatory }}"
    state: present
    login_unix_socket: "{{ login_unix_socket | default(omit) }}"
  when: is_root_password_set.rc == 0
# - name: "MariaDB: remove root remote access"

# - name: "MariaDB: remove the test database"
#   mysql_db:
#     name: test
#     state: absent
