AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4

Rails:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/OptionHash:
  Enabled: true

Style/Send:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: true

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals
  Enabled: true


Metrics/MethodLength:
  CountComments: false
  Max: 50

Metrics/ClassLength:
  CountComments: false
  Max: 500

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Max: 35

Style/IfUnlessModifier:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatStringToken:
  Enabled: false
