---
- name: "Add BrightBox repo (for latest Rubys)"
  apt_repository:
    repo: ppa:brightbox/ruby-ng
    update_cache: yes

- name: "Install Ruby"
  apt: pkg={{ item }} state=installed
  with_items:
  - ruby2.4
  - ruby2.4-dev

- name: "Additional software"
  apt: pkg={{ item }} state=installed
  with_items:
  - imagemagick
  - zlib1g-dev # Required for Nokogiri

- name: "Install Bundler"
  shell: gem install bundler --no-document

- name: "Install Gems"
  bundler:
    state: present
    gemfile: /srv/tgc/Gemfile
