fieldLayouts:
  8a97e738-7231-47bc-bc19-fbbadfa38e8d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 50ec1514-bf90-4ded-b96a-a87d667853a3 # Description
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3f56b509-b338-47f2-889d-fc66c7e1743e
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 9d452bf0-0ae9-4057-a2b1-88677f14c772
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 43fe5861-2468-405f-a0db-ef2dd77323f1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            type: craft\fieldlayoutelements\HorizontalRule
        name: Content
        sortOrder: 1
handle: series
name: Series
siteSettings:
  cd87a5c6-673c-4d81-82dd-77a22e5131e8:
    hasUrls: true
    template: preaching/_series
    uriFormat: 'preaching/{{ slug }}'
structure:
  maxLevels: 1
  uid: 87d819b9-6e25-4543-a371-17e4c4126dde
