---
- name: "Install uncomplicated firewall (UFW)"
  apt:
    name: ufw
    state: present

- name: "Allow SSH"
  ufw:
    rule: allow
    name: OpenSSH

- name: "Open up ports"
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - "80"
    - "443"
    - "3306"

- name: "Enable UFW"
  ufw:
    state: enabled
