tabs:
  -
    elements:
      -
        fieldUid: 54a27e66-233b-40bf-bc3d-39035cbe1260
        instructions: ''
        label: 'Title or role'
        required: ''
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
      -
        fieldUid: 36b0b273-d40e-42b1-9ac9-295058c46cd4
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
      -
        fieldUid: 50ec1514-bf90-4ded-b96a-a87d667853a3 # Description
        instructions: 'Keep it brief. One sentence is all you need here. This will be displayed below blog posts.'
        label: 'Short introduction'
        required: '1'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
      -
        fieldUid: 73b2998e-198b-4a74-9484-0b935083ce4a
        instructions: 'This is displayed on a profile page for a user (if enabled) - two paragraphs about the person including a testimony.'
        label: 'Long introduction'
        required: ''
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
    name: About
    sortOrder: 1
