contentColumnType: string(960)
fieldGroup: 51a71e36-16cc-46e3-9106-66e6ff4d8d62
handle: description
instructions: 'Short introduction to content. Will be displayed on social media, might be displayed on the page'
name: Description
searchable: false
settings:
  byteLimit: null
  charLimit: 240
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
