contentColumnType: boolean
fieldGroup: 30b75af0-c1c0-44d6-83c6-38f1d0a6dd50
handle: physicalLocation
instructions: ''
name: 'Physical location?'
searchable: false
settings:
  default: true
  offLabel: 'No'
  onLabel: 'Yes'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
