dateModified: 1603259867
email:
  fromEmail: james@globe.church
  fromName: 'The Globe Church'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  dashboard-begone:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  imager:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  imager-do-spaces-driver:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      assetPath: cr-assets
      publicPath: web
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: pro
  live: true
  name: 'The Globe Church'
  retryDuration: null
  schemaVersion: 3.5.13
  timeZone: UTC
users:
  allowPublicRegistration: false
  defaultGroup: ''
  photoSubpath: /avatars
  photoVolumeUid: fdcbfbe5-de93-49e6-b5f8-d867b6eb26c0
  requireEmailVerification: true
  suspendByDefault: false
