dateModified: 1619417976
email:
  fromEmail: james@globe.church
  fromName: 'The Globe Church'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  calendarize:
    edition: standard
    enabled: true
    schemaVersion: 1.3.0
  dashboard-begone:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 4.3.0
  imager:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  imager-do-spaces-driver:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      assetPath: cr-assets
      publicPath: web
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: pro
  live: true
  name: 'The Globe Church'
  retryDuration: null
  schemaVersion: 3.6.8
  timeZone: UTC
