--- 

- name: Setup server
  hosts: all
  become: true # become sudo
  pre_tasks:
    - name: "apt-get update"
      raw: apt-get update -qq
  roles:
    - general
    - nginx
    - ruby
    - postgres

- name: Webserver setup
  hosts: all
  roles:
    - gems
