name: Staging Build & Deploy


on:
  push:
    branches: [github-actions]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging_environment
      url: https://next.globe.church
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        host: ${{secrets.SSH_HOST}}
        username: ${{secrets.SSH_USER}}
        key: ${{secrets.SSH_KEY}}

        script: |
          cd /srv/next.globe.church/deploy
          mkdir test
          cd test
          git clone git@github.com:theglobechurch/tgc.git
