name: Staging Build & Deploy


on:
  push:
    branches: [github-actions]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: STAGING
      url: https://next.globe.church
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Here's the host ${{ secrets.test }}."
      - run: echo "Here's the host ${{ secrets.SSH_HOST }}."
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd /srv/next.globe.church/deploy
            mkdir test
            cd test
            git clone git@github.com:theglobechurch/tgc.git
