name: Staging Build & Deploy


on:
  push:
    branches: [github-actions]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: STAGING
      url: https://next.globe.church
    steps:
      # - name: Deploy
      #   uses: appleboy/ssh-action@v0.1.4
      #   with:
      #     host: ${{secrets.SSH_HOST}}
      #     username: ${{secrets.SSH_USER}}
      #     key: ${{secrets.SSH_KEY}}
      #     script: |
      #       mkdir -p /srv/next.globe.church/deploy/test
      #       cd /srv/next.globe.church/deploy/test
      #       git clone git@github.com:theglobechurch/tgc.git .
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Check out the source
        run: ssh staging 'cd /srv/next.globe.church/live && git fetch && git reset --hard origin/github-actions'

      - name: Composer install
        run: ssh staging 'cd /srv/next.globe.church/live && composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev'

      - name: Craft sync
        run: ssh staging 'cd /srv/next.globe.church/live && ./craft migrate/all --interactive=0 && ./craft project-config/sync --force'

      - name: NPM install
        run: ssh staging 'cd /srv/next.globe.church/live && npm install && npm run production'
